"""make url and post optional

Revision ID: 3c18fe23508e
Revises: 5c34e18a6bd0
Create Date: 2023-07-04 14:11:56.078201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c18fe23508e'
down_revision = '5c34e18a6bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project', 'post',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'post',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
